/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import com.fasterxml.jackson.databind.JavaType;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.awt.Component;
import java.awt.Frame;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JComponent;
import javax.swing.JList;
import javax.swing.SwingUtilities;

/**
 *
 * @author koller
 */
public class JGrammarFromWebSelector extends javax.swing.JDialog {

    private List<GrammarEntry> grammars;
    private Consumer<URL> fn;

    /**
     * Creates new form JGrammarFromWebSelector
     */
    public JGrammarFromWebSelector(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        getRootPane().setDefaultButton(bOk);
    }

    public static void withSelectedURL(URL grammarListURL, Frame parent, boolean modal, Consumer<URL> fn) throws IOException {
        ObjectMapper mapper = new ObjectMapper();
        JavaType type = mapper.getTypeFactory().constructCollectionType(List.class, GrammarEntry.class);
        List<GrammarEntry> grammars = mapper.readValue(grammarListURL, type);

        JGrammarFromWebSelector js = new JGrammarFromWebSelector(parent, modal);
        js.fn = fn;
        js.populate(grammars);
        js.setVisible(true);
    }

    private void populate(List<GrammarEntry> entries) {
        List<String> tooltips = new ArrayList<>();
        ComboboxToolTipRenderer renderer = new ComboboxToolTipRenderer();

        this.grammars = entries;

        cbGrammars.removeAllItems();
        cbGrammars.setRenderer(renderer);
        
        for (GrammarEntry entry : entries) {
            cbGrammars.addItem(entry.displayString());
            tooltips.add(entry.comment == null ? "" : entry.comment);
        }
        
        renderer.setTooltips(tooltips);
    }

    private static class GrammarEntry {

        public int id;
        public String name;
        public String comment;

        public GrammarEntry() {
        }

        public GrammarEntry(int id, String name, String comment) {
            this.id = id;
            this.name = name;
            this.comment = comment;
        }

        public String displayString() {
            return id + ": " + name;
        }

        public URL url() {
            try {
                return new URL(GuiMain.getGrammarServer() + "/rest/grammar_" + id + ".irtg");
            } catch (MalformedURLException ex) {
                // should never happen
                return null;
            }
        }

        @Override
        public String toString() {
            return "GrammarEntry{" + "id=" + id + ", name=" + name + ", comment=" + comment + '}';
        }

    }

    private static class ComboboxToolTipRenderer extends DefaultListCellRenderer {
        List<String> tooltips;

        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {

            JComponent comp = (JComponent) super.getListCellRendererComponent(list,
                    value, index, isSelected, cellHasFocus);

            if (-1 < index && null != value && null != tooltips) {
                list.setToolTipText(tooltips.get(index));
            }
            return comp;
        }

        public void setTooltips(List<String> tooltips) {
            this.tooltips = tooltips;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbGrammars = new javax.swing.JComboBox();
        bOk = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Load grammar from web repository");

        jLabel1.setText("Select grammar from web repository:");

        cbGrammars.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        bOk.setText("Ok");
        bOk.addActionListener(evt -> bOkActionPerformed(evt));

        bCancel.setText("Cancel");
        bCancel.addActionListener(evt -> bCancelActionPerformed(evt));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(cbGrammars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bOk)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bCancel)))
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbGrammars, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bOk)
                    .addComponent(bCancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOkActionPerformed
        GrammarEntry entry = grammars.get(cbGrammars.getSelectedIndex());
        SwingUtilities.invokeLater(() -> fn.accept(entry.url()));
        setVisible(false);
    }//GEN-LAST:event_bOkActionPerformed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_bCancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOk;
    private javax.swing.JComboBox cbGrammars;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
