/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import de.up.ling.irtg.InterpretedTreeAutomaton;
import de.up.ling.irtg.automata.TreeAutomaton;
import de.up.ling.irtg.automata.WeightedTree;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

/**
 *
 * @author koller
 */
public class JLanguageViewer extends javax.swing.JFrame {
    private TreeAutomaton automaton;
    private Iterator<WeightedTree> languageIterator;
    private long numTrees;
    private List<WeightedTree> cachedTrees;

    /**
     * Creates new form JLanguageViewer
     */
    public JLanguageViewer() {
        initComponents();
    }

    public void setAutomaton(TreeAutomaton automaton, InterpretedTreeAutomaton irtg) {
        this.automaton = automaton;

        derivationViewer.setInterpretedTreeAutomaton(irtg);
        languageIterator = automaton.sortedLanguageIterator();
        cachedTrees = new ArrayList<WeightedTree>();

        if (automaton.isCyclic()) {
            numTrees = -1;
            languageSizeLabel.setText("of INFINITY");
        } else {
            numTrees = automaton.countTrees();
            languageSizeLabel.setText("of " + numTrees);
        }

        goToTree(0);
    }

    private void goToTree(int treeNumber) {
        if (numTrees > -1) {
            if (treeNumber >= numTrees) {
                if (numTrees > Integer.MAX_VALUE) {
                    treeNumber = Integer.MAX_VALUE - 1;
                } else {
                    treeNumber = (int) numTrees - 1;
                }
            }
        }

        if (treeNumber < 0) {
            treeNumber = 0;
        }

        while (cachedTrees.size() <= treeNumber) {
            cachedTrees.add(languageIterator.next());
        }

        WeightedTree wt = cachedTrees.get(treeNumber);
        derivationViewer.displayDerivation(automaton.getSignature().resolve(wt.getTree()));
        weightLabel.setText("w = " + formatWeight(wt.getWeight()));
        treeIndex.setText(Integer.toString(treeNumber + 1));
    }

    private int getTreeIndex() {
        try {
            return Integer.parseInt(treeIndex.getText()) - 1;
        } catch (NumberFormatException e) {
            return 0;
        }
    }

    private String formatWeight(double weight) {
        return Double.toString(weight);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        treeViewer = new javax.swing.JPanel();
        derivationViewer = new de.up.ling.irtg.gui.JDerivationViewer();
        controls = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        leftButton = new javax.swing.JButton();
        treeIndex = new javax.swing.JTextField();
        rightButton = new javax.swing.JButton();
        languageSizeLabel = new javax.swing.JLabel();
        weightLabel = new javax.swing.JLabel();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        org.jdesktop.layout.GroupLayout treeViewerLayout = new org.jdesktop.layout.GroupLayout(treeViewer);
        treeViewer.setLayout(treeViewerLayout);
        treeViewerLayout.setHorizontalGroup(
            treeViewerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(treeViewerLayout.createSequentialGroup()
                .addContainerGap()
                .add(derivationViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        treeViewerLayout.setVerticalGroup(
            treeViewerLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(treeViewerLayout.createSequentialGroup()
                .addContainerGap()
                .add(derivationViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel1.setText("Derivation #");

        leftButton.setText("<");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        treeIndex.setText("jTextField1");
        treeIndex.setMinimumSize(new java.awt.Dimension(84, 28));
        treeIndex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeIndexActionPerformed(evt);
            }
        });

        rightButton.setText(">");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        languageSizeLabel.setText("of INFINITY");

        weightLabel.setText("weight");

        org.jdesktop.layout.GroupLayout controlsLayout = new org.jdesktop.layout.GroupLayout(controls);
        controls.setLayout(controlsLayout);
        controlsLayout.setHorizontalGroup(
            controlsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(controlsLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(leftButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 41, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(treeIndex, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(rightButton, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(languageSizeLabel)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(weightLabel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 105, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        controlsLayout.setVerticalGroup(
            controlsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, controlsLayout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(controlsLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(leftButton)
                    .add(treeIndex, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(rightButton)
                    .add(languageSizeLabel)
                    .add(weightLabel))
                .add(7, 7, 7))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(treeViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(controls, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(treeViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(controls, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 42, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed
        goToTree(getTreeIndex() - 1);
    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed
        goToTree(getTreeIndex() + 1);
    }//GEN-LAST:event_rightButtonActionPerformed

    private void treeIndexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeIndexActionPerformed
        goToTree(getTreeIndex());
    }//GEN-LAST:event_treeIndexActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;




                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JLanguageViewer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JLanguageViewer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JLanguageViewer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JLanguageViewer.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JLanguageViewer().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controls;
    private de.up.ling.irtg.gui.JDerivationViewer derivationViewer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel languageSizeLabel;
    private javax.swing.JButton leftButton;
    private javax.swing.JButton rightButton;
    private javax.swing.JTextField treeIndex;
    private javax.swing.JPanel treeViewer;
    private javax.swing.JLabel weightLabel;
    // End of variables declaration//GEN-END:variables
}
