/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import java.awt.Color;
import java.awt.Component;
import java.lang.reflect.Field;
import java.util.List;
import java.util.Vector;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author koller
 */
public class JTableDialog<E> extends javax.swing.JDialog {
    private DefaultTableModel model;

    /**
     * Creates new form JTableDialog
     */
    public JTableDialog(String title, List<E> data) {
        super();
        setTitle(title);

        initComponents();
        fillTable(data);
    }

    private void fillTable(List<E> data) {
        if (data != null && !data.isEmpty()) {
            E first = data.get(0);

            Vector<String> columnIdentifiers = new Vector<String>();
            Field[] fields = first.getClass().getDeclaredFields();
            for (int i = 0; i < fields.length; i++) {
                columnIdentifiers.add(fields[i].getName());
            }

            model = new DefaultTableModel();
            table.setModel(model);
            model.setColumnIdentifiers(columnIdentifiers);

            for (E element : data) {
                Vector<String> row = new Vector<String>();
                for (int i = 0; i < fields.length; i++) {
                    try {
                        row.add(fields[i].get(element).toString());
                    } catch (Exception ex) {
                        row.add("---");
                    }
                }

                model.addRow(row);
            }

            final Color alternateRowColor = new Color(204, 229, 255);
            table.setDefaultRenderer(Object.class, new TableCellRenderer() {
                private DefaultTableCellRenderer DEFAULT_RENDERER = new DefaultTableCellRenderer();

                @Override
                public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                    Component c = DEFAULT_RENDERER.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
                    if (row % 2 == 0) {
                        c.setBackground(Color.WHITE);
                    } else {
                        c.setBackground(alternateRowColor);
                    }
                    return c;
                }
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setViewportView(table);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
