/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import de.saar.basic.StringTools;
import de.up.ling.irtg.algebra.Algebra;
import de.up.ling.irtg.codec.AlgebraStringRepresentationOutputCodec;
import de.up.ling.irtg.codec.OutputCodec;
import de.up.ling.irtg.util.GuiUtils;
import java.awt.Dimension;
import javax.swing.SwingUtilities;
import javax.swing.JComponent;
import java.awt.Color;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.Supplier;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.ToolTipManager;

/**
 *
 * @author koller
 */
public class JVisualizationViewer extends javax.swing.JFrame {

    private boolean hasBeenPacked = false; // window has been packed once -- after this, only allow manual size changes


    /**
     * Creates new form JVisualizationViewer, displaying the object as visualized
     * by the algebra.
     * @param alg
     * @param object
     */
    public JVisualizationViewer(Algebra alg, String object) {
        initComponents();

        JComponent vis;
        try {
            Object value = alg.parseString(object);
            vis = alg.visualize(value);

            Map<String, Supplier<String>> popupEntries = new LinkedHashMap<>();

            OutputCodec oc = new AlgebraStringRepresentationOutputCodec(alg);
            popupEntries.put(oc.getMetadata().description(), oc.asStringSupplier(value));

            for (OutputCodec codec : OutputCodec.getOutputCodecs(value.getClass())) {
                if (codec.getMetadata().displayInPopup()) {
                    popupEntries.put(codec.getMetadata().description(), codec.asStringSupplier(value));
                }
            }

            new PopupMenu(popupEntries).addAsMouseListener(vis);
        } catch (Exception e) {
            vis = makeErrorComponent(e);
            e.printStackTrace(System.err);
        }

        valuePanel.add(sp(vis));

        if (!GuiMain.isMac()) {
            GuiUtils.replaceMetaByCtrl(jMenuBar1);
        }
    }
    
    private JComponent makeErrorComponent(Exception e) {
        JLabel ret = new JLabel("<Can't evaluate: " + e.toString() + ">");

        String tooltipText = "<html>" + e + "<br>" + StringTools.join(Arrays.asList(e.getStackTrace()), "<br>\n") + "</html>";

        ret.setToolTipText(tooltipText);
        ToolTipManager.sharedInstance().setDismissDelay(Integer.MAX_VALUE);

        return ret;
    }

    
    private JComponent sp(JComponent comp) {
        JScrollPane ret = new JScrollPane(comp, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        ret.setBackground(Color.white);
        return ret;
    }
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);

        // For some reason, new window doesn't always get the focus as it should
        // (at least on Mac). Request it explicitly to make sure hotkeys work.
        SwingUtilities.invokeLater(() -> {
            requestFocus();
        });
    }

    @Override
    public void pack() {
        super.pack(); //To change body of generated methods, choose Tools | Templates.
        hasBeenPacked = true;
    }

    @Override
    public Dimension getPreferredSize() {
        // pin window size to current size => layout of contents does not change window size
        // -- an exception is the very first time the window is packed, then allow it to get correct size
        if (hasBeenPacked) {
            return getSize();
        } else {
            return super.getPreferredSize();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        visViewer = new javax.swing.JPanel();
        valuePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                handleResize(evt);
            }
        });

        visViewer.setLayout(new javax.swing.BoxLayout(visViewer, javax.swing.BoxLayout.LINE_AXIS));

        valuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Value"));
        valuePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                valuePanelhandleValuePanelResized(evt);
            }
        });
        valuePanel.setLayout(new java.awt.BorderLayout());
        visViewer.add(valuePanel);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(visViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(visViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_handleResize

    }//GEN-LAST:event_handleResize

    private void valuePanelhandleValuePanelResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_valuePanelhandleValuePanelResized
        //        valuePanel.setPreferredSize(valuePanel.getSize());
    }//GEN-LAST:event_valuePanelhandleValuePanelResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel valuePanel;
    private javax.swing.JPanel visViewer;
    // End of variables declaration//GEN-END:variables
}
