/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import com.bric.window.WindowMenu;
import de.up.ling.irtg.Interpretation;
import de.up.ling.irtg.InterpretedTreeAutomaton;
import de.up.ling.irtg.algebra.Algebra;
import de.up.ling.irtg.automata.language_iteration.SortedLanguageIterator;
import de.up.ling.irtg.automata.TreeAutomaton;
import de.up.ling.irtg.automata.WeightedTree;
import static de.up.ling.irtg.gui.GuiMain.log;
import de.up.ling.irtg.util.GuiUtils;
import de.up.ling.irtg.util.Util;
import static de.up.ling.irtg.util.Util.formatTimeSince;
import de.up.ling.tree.Tree;
import java.awt.Component;
import java.awt.Dimension;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import javax.swing.SwingUtilities;
import static de.up.ling.irtg.gui.GuiMain.log;
import javax.swing.JComponent;
import static de.up.ling.irtg.gui.GuiMain.log;
import static de.up.ling.irtg.gui.GuiMain.log;
import static de.up.ling.irtg.gui.GuiMain.log;
import static de.up.ling.irtg.gui.GuiMain.log;
import static de.up.ling.irtg.gui.GuiMain.log;
import static de.up.ling.irtg.gui.GuiMain.log;
import java.awt.Color;
import javax.swing.JScrollPane;

/**
 *
 * @author koller
 */
public class JVisualizationViewer extends javax.swing.JFrame {

    private TreeAutomaton automaton;
    private SortedLanguageIterator languageIterator;
    private long numTrees;
    private List<WeightedTree> cachedTrees;
    private InterpretedTreeAutomaton currentIrtg;
    private Tree<String> currentTree;
    private boolean hasBeenPacked = false; // window has been packed once -- after this, only allow manual size changes


    /**
     * Creates new form JLanguageViewer
     * @param vis
     */
    public JVisualizationViewer(JComponent vis) {
        initComponents();


        valuePanel.add(sp(vis));

        if (!GuiMain.isMac()) {
            GuiUtils.replaceMetaByCtrl(jMenuBar1);
        }
    }

    
    private JComponent sp(JComponent comp) {
        JScrollPane ret = new JScrollPane(comp, JScrollPane.VERTICAL_SCROLLBAR_AS_NEEDED, JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        ret.setBackground(Color.white);
        return ret;
    }
    
    @Override
    public void setVisible(boolean b) {
        super.setVisible(b);

        // For some reason, new window doesn't always get the focus as it should
        // (at least on Mac). Request it explicitly to make sure hotkeys work.
        SwingUtilities.invokeLater(() -> {
            requestFocus();
        });
    }

    @Override
    public void pack() {
        super.pack(); //To change body of generated methods, choose Tools | Templates.
        hasBeenPacked = true;
    }

    @Override
    public Dimension getPreferredSize() {
        // pin window size to current size => layout of contents does not change window size
        // -- an exception is the very first time the window is packed, then allow it to get correct size
        if (hasBeenPacked) {
            return getSize();
        } else {
            return super.getPreferredSize();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jSeparator3 = new javax.swing.JSeparator();
        visViewer = new javax.swing.JPanel();
        valuePanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                handleResize(evt);
            }
        });

        visViewer.setLayout(new javax.swing.BoxLayout(visViewer, javax.swing.BoxLayout.LINE_AXIS));

        valuePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Value"));
        valuePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                valuePanelhandleValuePanelResized(evt);
            }
        });
        valuePanel.setLayout(new java.awt.BorderLayout());
        visViewer.add(valuePanel);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(visViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 578, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(visViewer, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void handleResize(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_handleResize

    }//GEN-LAST:event_handleResize

    private void valuePanelhandleValuePanelResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_valuePanelhandleValuePanelResized
        //        valuePanel.setPreferredSize(valuePanel.getSize());
    }//GEN-LAST:event_valuePanelhandleValuePanelResized


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel valuePanel;
    private javax.swing.JPanel visViewer;
    // End of variables declaration//GEN-END:variables
}
