/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.up.ling.irtg.gui;

import de.up.ling.irtg.InterpretedTreeAutomaton;
import de.up.ling.tree.Tree;

/**
 *
 * @author koller
 */
public class MultiDerivationViewer extends javax.swing.JPanel {
    /**
     * Creates new form MultiDerivationViewer
     */
    public MultiDerivationViewer() {
        initComponents();
    }
    
    public void displayDerivation(Tree<String> derivationTree) {
        jDerivationViewer1.displayDerivation(derivationTree);
        jDerivationViewer2.displayDerivation(derivationTree);
    }
    
    public void setInterpretedTreeAutomaton(InterpretedTreeAutomaton irtg) {
        jDerivationViewer1.setInterpretedTreeAutomaton(irtg);
        jDerivationViewer2.setInterpretedTreeAutomaton(irtg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jDerivationViewer1 = new de.up.ling.irtg.gui.JDerivationViewer();
        jDerivationViewer2 = new de.up.ling.irtg.gui.JDerivationViewer();

        jSplitPane1.setLeftComponent(jDerivationViewer1);
        jSplitPane1.setRightComponent(jDerivationViewer2);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSplitPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.up.ling.irtg.gui.JDerivationViewer jDerivationViewer1;
    private de.up.ling.irtg.gui.JDerivationViewer jDerivationViewer2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
